server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    sentOrdersTopic: sent_orders
    paymentTopic: payed_orders
    kafkaMessageGroupId: kafka-message-group-id
