server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    orderTopic: new_orders
    paymentTopic: payed_orders
    kafkaMessageGroupId: "kafka-message-group-id"

