server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:19092, localhost:19093, localhost:19094

app:
  kafka:
    sentOrdersTopic: sent_orders
    kafkaMessageGroupId: notification-group
